# Generated by Django 3.2.4 on 2021-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
