# Generated by Django 3.2.4 on 2021-06-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_alter_temp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advert_to_attribute', to='adverts.advertsadvert')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_to_advert', to='adverts.attribute')),
            ],
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
