# Generated by Django 3.2.4 on 2021-06-18 15:38
from cities_light.models import City
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_auto_20210617_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertsadvert',
            name='value',
            field=models.ManyToManyField(related_name='value_set', to='adverts.Value'),
        ),
    ]

    City
